### ISSUE TITLE
Configuring sink using JSON

### ISSUE THREAD

**Issue by FantasticFiasco** [jamesbascle/serilog.LogglyBulk#2]
Hi!

There is a proposal over at [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration/issues/53) where sink developers would be able to specify an extension point specially designed to support JSON configuration. If this is something you would find beneficial for your sink, please give a thumbs up or something. If not, have a nice day and continue being awesome!

**Comment by jamesbascle** [comment]
I am not particularly worried about it one way or another.  I would not be opposed to a well written PR that does such a thing if it were implemented in the core lib.

**Comment by FantasticFiasco** [comment]
You are correct, the PR is not a well written specification, and for that I am sorry. It is a tl;rd; of a feature that hopefully would benefit some sink. But if you haven't felt the pain of the current compatibility, it is not for you.

Have a nice day!
